version: '3.8'
services:
  api-server:
    image: raulik/tcsfw-api-server
    environment:
      - TCSFW_SERVER_API_KEY=${TCSFW_SERVER_API_KEY}

  api-proxy:
    build:
      context: ./api-proxy
      args:
        SERVER: api-server

  frontend:
    build: .
    environment:
      - VITE_API_PROXY=http://api-proxy:8181
      - VITE_API_WS_PROXY=ws://api-proxy:8181
    ports:
      - "5173:5173"
    depends_on:
      - api-proxy
      - api-server
