services:
  api-server:
    image: tcsfw/api-server

  api-proxy:
    build:
      context: ./api-proxy
      args:
        USERS: ${USERS}
        SERVER: api-server

  web-server:
    build: .
    environment:
      - VITE_API_PROXY=http://api-proxy:8181
    ports:
      - "5173:5173"
    depends_on:
      - api-proxy
      - api-server
